### ISSUE TITLE
Extend gestures count to 9

### ISSUE THREAD

**Issue by ChamikaRohan** [ChamikaRohan/DeepLearning-Gesture-based-HCI#2]
Try to extend the gestures count to 9 since we do not have enough functionalities for some applications.

**Comment by Chiara-Vanderlan** [comment]
Gesture count was increased up to 9.  Newly added gesture(9th gesture) is shown below. 
![3 fingers gesture](https://github.com/ChamikaRohan/DeepLearning-Gesture-based-HCI/assets/115263438/52c660b9-2323-40ea-878e-6ad33627772f)
