### ISSUE TITLE
Extend the gestures count to 10

### ISSUE THREAD

**Issue by ChamikaRohan** [ChamikaRohan/DeepLearning-Gesture-based-HCI#4]
Try to extend the gestures count to 10, then we can have more freedom when developing the backend actions.

**Comment by Chiara-Vanderlan** [comment]
The gesture count was increased to 10. A newly added gesture (10th gesture, named as scissors) is shown below.

![2](https://github.com/ChamikaRohan/DeepLearning-Gesture-based-HCI/assets/115263438/dba3d2da-d37e-4322-98d0-0f6322aeada5)
